class KeywordsInAction {
    public static void main(String[] args) {

  System.out.println("void");
   System.out.println("const");
  System.out.println("final");
 System.out.println("import");
   System.out.println("else");
     System.out.println("class");
   System.out.println("native");
    System.out.println("public");
    System.out.println("strictfp");
    System.out.println("boolean");
    System.out.println("throw");
  System.out.println("enum");
   System.out.println("extends");
   System.out.println("char");
    System.out.println("implements");
   System.out.println("try");
   System.out.println("byte");
   System.out.println("switch");
   System.out.println("static");
   System.out.println("finally");
    System.out.println("super");
     System.out.println("float");
   System.out.println("long");
  System.out.println("native");
    System.out.println("protected");
   System.out.println("return");
    System.out.println("new");
    System.out.println("package");
      System.out.println("short");
     System.out.println("if");
     System.out.println("this");
   System.out.println("case");
   System.out.println("default");
   System.out.println("catch");
  System.out.println("throws");
 System.out.println("instanceof"); 
 System.out.println("transient");
    System.out.println("for");
   System.out.println("while");
     System.out.println("do");
   System.out.println("finally");
   System.out.println("float");
   System.out.println("super");
    System.out.println("long");
    System.out.println("assert"); 
	System.out.println("static");
     System.out.println("final");
     System.out.println("interface");
    System.out.println("try");
     System.out.println("byte");
    }
}